Resources:

  ELBCreate:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      AvailabilityZones:
        - eu-west-2a
        - eu-west-2b
      LoadBalancerName: "Friday-project-2-ELB"
      Listeners:
      - LoadBalancerPort: '80'
        InstancePort: '80'
        Protocol: HTTP
      HealthCheck:
        Target: HTTP:80/
        HealthyThreshold: '3'
        UnhealthyThreshold: '5'
        Interval: '30'
        Timeout: '5'
      SecurityGroups: 
       - "sg-a005e8c0"
  

  LCCreate: 
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      LaunchConfigurationName: "friday-project-2-LC" 
      ImageId: "ami-025c83c9c19b07748"
      InstanceType: "t2.micro"
      IamInstanceProfile: "ec2-apigateway-access"
      SecurityGroups: 
      - "sg-a005e8c0"
      

  ASGCreate:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties: 
      AvailabilityZones: 
        - eu-west-2a
        - eu-west-2b
      LaunchConfigurationName: "friday-project-2-LC"
      MinSize: "2"
      MaxSize: "2"
      LoadBalancerNames: 
      - "Friday-project-2-ELB"
      MetricsCollection: 
        - 
          Granularity: "1Minute"
          Metrics: 
            - "GroupMinSize"
            - "GroupMaxSize"
      Tags:
        - Key: Name
          Value: Friday-project-2-ASG
          PropagateAtLaunch: "true"
        - Key: Purpose
          Value: WebServerGroup
          PropagateAtLaunch: "false"
    DependsOn:
    - LCCreate
      #SecurityGroupIds: "sg-a005e8c0"