
version: '3.7'
services:

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes: 
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    ports:
      - target: 80
        published: 80
        protocol: tcp
    deploy:
      replicas: 3
    depends_on: 
      - service1


  service1:
    image: 127.0.0.1:5000/service1
    build:
        context: .
        dockerfile: Dockerfile
      image: 127.0.0.1:5000/service1